package com.ankamagames.dofus.network
{
   import com.ankamagames.dofus.network.types.common.basic.StatisticData;
   import com.ankamagames.dofus.network.types.common.basic.StatisticDataBoolean;
   import com.ankamagames.dofus.network.types.common.basic.StatisticDataByte;
   import com.ankamagames.dofus.network.types.common.basic.StatisticDataInt;
   import com.ankamagames.dofus.network.types.common.basic.StatisticDataShort;
   import com.ankamagames.dofus.network.types.common.basic.StatisticDataString;
   import com.ankamagames.dofus.network.types.game.achievement.AchievementAchieved;
   import com.ankamagames.dofus.network.types.game.achievement.AchievementAchievedRewardable;
   import com.ankamagames.dofus.network.types.game.actions.fight.AbstractFightDispellableEffect;
   import com.ankamagames.dofus.network.types.game.actions.fight.FightTemporaryBoostEffect;
   import com.ankamagames.dofus.network.types.game.actions.fight.FightTemporaryBoostStateEffect;
   import com.ankamagames.dofus.network.types.game.actions.fight.FightTemporaryBoostWeaponDamagesEffect;
   import com.ankamagames.dofus.network.types.game.actions.fight.FightTemporarySpellBoostEffect;
   import com.ankamagames.dofus.network.types.game.actions.fight.FightTemporarySpellImmunityEffect;
   import com.ankamagames.dofus.network.types.game.actions.fight.FightTriggeredEffect;
   import com.ankamagames.dofus.network.types.game.approach.ServerSessionConstant;
   import com.ankamagames.dofus.network.types.game.approach.ServerSessionConstantInteger;
   import com.ankamagames.dofus.network.types.game.approach.ServerSessionConstantLong;
   import com.ankamagames.dofus.network.types.game.approach.ServerSessionConstantString;
   import com.ankamagames.dofus.network.types.game.character.CharacterMinimalAllianceInformations;
   import com.ankamagames.dofus.network.types.game.character.CharacterMinimalGuildInformations;
   import com.ankamagames.dofus.network.types.game.character.CharacterMinimalPlusLookAndGradeInformations;
   import com.ankamagames.dofus.network.types.game.character.CharacterMinimalPlusLookInformations;
   import com.ankamagames.dofus.network.types.game.character.choice.CharacterBaseInformations;
   import com.ankamagames.dofus.network.types.game.character.choice.CharacterHardcoreOrEpicInformations;
   import com.ankamagames.dofus.network.types.game.character.debt.DebtInformation;
   import com.ankamagames.dofus.network.types.game.character.debt.KamaDebtInformation;
   import com.ankamagames.dofus.network.types.game.character.status.PlayerStatus;
   import com.ankamagames.dofus.network.types.game.character.status.PlayerStatusExtended;
   import com.ankamagames.dofus.network.types.game.context.EntityDispositionInformations;
   import com.ankamagames.dofus.network.types.game.context.FightEntityDispositionInformations;
   import com.ankamagames.dofus.network.types.game.context.GameContextActorInformations;
   import com.ankamagames.dofus.network.types.game.context.GameContextActorPositionInformations;
   import com.ankamagames.dofus.network.types.game.context.GameRolePlayTaxCollectorInformations;
   import com.ankamagames.dofus.network.types.game.context.IdentifiedEntityDispositionInformations;
   import com.ankamagames.dofus.network.types.game.context.MapCoordinates;
   import com.ankamagames.dofus.network.types.game.context.MapCoordinatesAndId;
   import com.ankamagames.dofus.network.types.game.context.MapCoordinatesExtended;
   import com.ankamagames.dofus.network.types.game.context.TaxCollectorStaticExtendedInformations;
   import com.ankamagames.dofus.network.types.game.context.TaxCollectorStaticInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.BaseSpawnMonsterInformation;
   import com.ankamagames.dofus.network.types.game.context.fight.FightAllianceTeamInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.FightResultAdditionalData;
   import com.ankamagames.dofus.network.types.game.context.fight.FightResultExperienceData;
   import com.ankamagames.dofus.network.types.game.context.fight.FightResultFighterListEntry;
   import com.ankamagames.dofus.network.types.game.context.fight.FightResultListEntry;
   import com.ankamagames.dofus.network.types.game.context.fight.FightResultMutantListEntry;
   import com.ankamagames.dofus.network.types.game.context.fight.FightResultPlayerListEntry;
   import com.ankamagames.dofus.network.types.game.context.fight.FightResultPvpData;
   import com.ankamagames.dofus.network.types.game.context.fight.FightResultTaxCollectorListEntry;
   import com.ankamagames.dofus.network.types.game.context.fight.FightTeamInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.FightTeamMemberCharacterInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.FightTeamMemberEntityInformation;
   import com.ankamagames.dofus.network.types.game.context.fight.FightTeamMemberInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.FightTeamMemberMonsterInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.FightTeamMemberTaxCollectorInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.FightTeamMemberWithAllianceCharacterInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.GameContextBasicSpawnInformation;
   import com.ankamagames.dofus.network.types.game.context.fight.GameContextSummonsInformation;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightAIInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightCharacterInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightEntityInformation;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightFighterEntityLightInformation;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightFighterInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightFighterLightInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightFighterMonsterLightInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightFighterNamedInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightFighterNamedLightInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightFighterTaxCollectorLightInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightMinimalStats;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightMinimalStatsPreparation;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightMonsterInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightMonsterWithAlignmentInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightMutantInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.GameFightTaxCollectorInformations;
   import com.ankamagames.dofus.network.types.game.context.fight.SpawnCharacterInformation;
   import com.ankamagames.dofus.network.types.game.context.fight.SpawnCompanionInformation;
   import com.ankamagames.dofus.network.types.game.context.fight.SpawnInformation;
   import com.ankamagames.dofus.network.types.game.context.fight.SpawnMonsterInformation;
   import com.ankamagames.dofus.network.types.game.context.fight.SpawnScaledMonsterInformation;
   import com.ankamagames.dofus.network.types.game.context.roleplay.AllianceInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.BasicAllianceInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.BasicGuildInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.BasicNamedAllianceInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayActorInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayCharacterInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayGroupMonsterInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayGroupMonsterWaveInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayHumanoidInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayMerchantInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayMountInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayMutantInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayNamedActorInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayNpcInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayNpcWithQuestInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayPortalInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayPrismInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GameRolePlayTreasureHintInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GroupMonsterStaticInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GroupMonsterStaticInformationsWithAlternatives;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GuildInAllianceInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.GuildInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.HumanInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.HumanOption;
   import com.ankamagames.dofus.network.types.game.context.roleplay.HumanOptionAlliance;
   import com.ankamagames.dofus.network.types.game.context.roleplay.HumanOptionEmote;
   import com.ankamagames.dofus.network.types.game.context.roleplay.HumanOptionFollowers;
   import com.ankamagames.dofus.network.types.game.context.roleplay.HumanOptionGuild;
   import com.ankamagames.dofus.network.types.game.context.roleplay.HumanOptionObjectUse;
   import com.ankamagames.dofus.network.types.game.context.roleplay.HumanOptionOrnament;
   import com.ankamagames.dofus.network.types.game.context.roleplay.HumanOptionSkillUse;
   import com.ankamagames.dofus.network.types.game.context.roleplay.HumanOptionTitle;
   import com.ankamagames.dofus.network.types.game.context.roleplay.breach.BreachBranch;
   import com.ankamagames.dofus.network.types.game.context.roleplay.breach.ExtendedBreachBranch;
   import com.ankamagames.dofus.network.types.game.context.roleplay.breach.ExtendedLockedBreachBranch;
   import com.ankamagames.dofus.network.types.game.context.roleplay.party.PartyInvitationMemberInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.party.PartyMemberArenaInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.party.PartyMemberInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.party.entity.PartyEntityBaseInformation;
   import com.ankamagames.dofus.network.types.game.context.roleplay.party.entity.PartyEntityMemberInformation;
   import com.ankamagames.dofus.network.types.game.context.roleplay.quest.QuestActiveDetailedInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.quest.QuestActiveInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.quest.QuestObjectiveInformations;
   import com.ankamagames.dofus.network.types.game.context.roleplay.quest.QuestObjectiveInformationsWithCompletion;
   import com.ankamagames.dofus.network.types.game.context.roleplay.treasureHunt.PortalInformation;
   import com.ankamagames.dofus.network.types.game.context.roleplay.treasureHunt.TreasureHuntStep;
   import com.ankamagames.dofus.network.types.game.context.roleplay.treasureHunt.TreasureHuntStepDig;
   import com.ankamagames.dofus.network.types.game.context.roleplay.treasureHunt.TreasureHuntStepFight;
   import com.ankamagames.dofus.network.types.game.context.roleplay.treasureHunt.TreasureHuntStepFollowDirection;
   import com.ankamagames.dofus.network.types.game.context.roleplay.treasureHunt.TreasureHuntStepFollowDirectionToHint;
   import com.ankamagames.dofus.network.types.game.context.roleplay.treasureHunt.TreasureHuntStepFollowDirectionToPOI;
   import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffect;
   import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffectCreature;
   import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffectDate;
   import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffectDice;
   import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffectDuration;
   import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffectInteger;
   import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffectLadder;
   import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffectMinMax;
   import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffectMount;
   import com.ankamagames.dofus.network.types.game.data.items.effects.ObjectEffectString;
   import com.ankamagames.dofus.network.types.game.friend.AcquaintanceInformation;
   import com.ankamagames.dofus.network.types.game.friend.AcquaintanceOnlineInformation;
   import com.ankamagames.dofus.network.types.game.friend.FriendInformations;
   import com.ankamagames.dofus.network.types.game.friend.FriendOnlineInformations;
   import com.ankamagames.dofus.network.types.game.friend.FriendSpouseInformations;
   import com.ankamagames.dofus.network.types.game.friend.FriendSpouseOnlineInformations;
   import com.ankamagames.dofus.network.types.game.friend.IgnoredInformations;
   import com.ankamagames.dofus.network.types.game.friend.IgnoredOnlineInformations;
   import com.ankamagames.dofus.network.types.game.guild.tax.TaxCollectorComplementaryInformations;
   import com.ankamagames.dofus.network.types.game.guild.tax.TaxCollectorGuildInformations;
   import com.ankamagames.dofus.network.types.game.guild.tax.TaxCollectorInformations;
   import com.ankamagames.dofus.network.types.game.guild.tax.TaxCollectorLootInformations;
   import com.ankamagames.dofus.network.types.game.guild.tax.TaxCollectorWaitingForHelpInformations;
   import com.ankamagames.dofus.network.types.game.house.AccountHouseInformations;
   import com.ankamagames.dofus.network.types.game.house.HouseGuildedInformations;
   import com.ankamagames.dofus.network.types.game.house.HouseInformations;
   import com.ankamagames.dofus.network.types.game.house.HouseInformationsForGuild;
   import com.ankamagames.dofus.network.types.game.house.HouseInformationsInside;
   import com.ankamagames.dofus.network.types.game.house.HouseInstanceInformations;
   import com.ankamagames.dofus.network.types.game.house.HouseOnMapInformations;
   import com.ankamagames.dofus.network.types.game.idol.Idol;
   import com.ankamagames.dofus.network.types.game.idol.PartyIdol;
   import com.ankamagames.dofus.network.types.game.interactive.InteractiveElement;
   import com.ankamagames.dofus.network.types.game.interactive.InteractiveElementNamedSkill;
   import com.ankamagames.dofus.network.types.game.interactive.InteractiveElementSkill;
   import com.ankamagames.dofus.network.types.game.interactive.InteractiveElementWithAgeBonus;
   import com.ankamagames.dofus.network.types.game.interactive.skill.SkillActionDescription;
   import com.ankamagames.dofus.network.types.game.interactive.skill.SkillActionDescriptionCollect;
   import com.ankamagames.dofus.network.types.game.interactive.skill.SkillActionDescriptionCraft;
   import com.ankamagames.dofus.network.types.game.interactive.skill.SkillActionDescriptionTimed;
   import com.ankamagames.dofus.network.types.game.mount.UpdateMountBooleanCharacteristic;
   import com.ankamagames.dofus.network.types.game.mount.UpdateMountCharacteristic;
   import com.ankamagames.dofus.network.types.game.mount.UpdateMountIntegerCharacteristic;
   import com.ankamagames.dofus.network.types.game.paddock.PaddockBuyableInformations;
   import com.ankamagames.dofus.network.types.game.paddock.PaddockGuildedInformations;
   import com.ankamagames.dofus.network.types.game.presets.EntitiesPreset;
   import com.ankamagames.dofus.network.types.game.presets.ForgettableSpellsPreset;
   import com.ankamagames.dofus.network.types.game.presets.FullStatsPreset;
   import com.ankamagames.dofus.network.types.game.presets.IconNamedPreset;
   import com.ankamagames.dofus.network.types.game.presets.IdolsPreset;
   import com.ankamagames.dofus.network.types.game.presets.ItemsPreset;
   import com.ankamagames.dofus.network.types.game.presets.Preset;
   import com.ankamagames.dofus.network.types.game.presets.PresetsContainerPreset;
   import com.ankamagames.dofus.network.types.game.presets.SpellsPreset;
   import com.ankamagames.dofus.network.types.game.presets.StatsPreset;
   import com.ankamagames.dofus.network.types.game.prism.AllianceInsiderPrismInformation;
   import com.ankamagames.dofus.network.types.game.prism.AlliancePrismInformation;
   import com.ankamagames.dofus.network.types.game.prism.PrismGeolocalizedInformation;
   import com.ankamagames.dofus.network.types.game.prism.PrismInformation;
   import com.ankamagames.dofus.network.types.game.prism.PrismSubareaEmptyInfo;
   import com.ankamagames.dofus.network.types.game.shortcut.Shortcut;
   import com.ankamagames.dofus.network.types.game.shortcut.ShortcutEmote;
   import com.ankamagames.dofus.network.types.game.shortcut.ShortcutEntitiesPreset;
   import com.ankamagames.dofus.network.types.game.shortcut.ShortcutObject;
   import com.ankamagames.dofus.network.types.game.shortcut.ShortcutObjectIdolsPreset;
   import com.ankamagames.dofus.network.types.game.shortcut.ShortcutObjectItem;
   import com.ankamagames.dofus.network.types.game.shortcut.ShortcutObjectPreset;
   import com.ankamagames.dofus.network.types.game.shortcut.ShortcutSmiley;
   import com.ankamagames.dofus.network.types.game.shortcut.ShortcutSpell;
   import com.ankamagames.dofus.network.types.game.social.AbstractSocialGroupInfos;
   import com.ankamagames.dofus.network.types.game.social.AllianceFactSheetInformations;
   import com.ankamagames.dofus.network.types.game.social.AlliancedGuildFactSheetInformations;
   import com.ankamagames.dofus.network.types.game.social.GuildFactSheetInformations;
   import com.ankamagames.dofus.network.types.game.social.GuildInAllianceVersatileInformations;
   import com.ankamagames.dofus.network.types.game.social.GuildInsiderFactSheetInformations;
   import com.ankamagames.dofus.network.types.game.social.GuildVersatileInformations;
   import com.ankamagames.jerakine.managers.StoreDataManager;
   import flash.utils.Dictionary;
   
   public class ProtocolTypeManager
   {
      
      private static const _typesTypes:Dictionary = new Dictionary();
      
      {
         _typesTypes[9017] = CharacterMinimalPlusLookInformations;
         _typesTypes[9272] = CharacterBaseInformations;
         _typesTypes[213] = PartyMemberInformations;
         _typesTypes[6321] = PartyMemberArenaInformations;
         _typesTypes[7121] = PartyInvitationMemberInformations;
         _typesTypes[5330] = CharacterHardcoreOrEpicInformations;
         _typesTypes[3916] = CharacterMinimalGuildInformations;
         _typesTypes[300] = CharacterMinimalAllianceInformations;
         _typesTypes[9668] = CharacterMinimalPlusLookAndGradeInformations;
         _typesTypes[9272] = CharacterBaseInformations;
         _typesTypes[213] = PartyMemberInformations;
         _typesTypes[6321] = PartyMemberArenaInformations;
         _typesTypes[7121] = PartyInvitationMemberInformations;
         _typesTypes[5330] = CharacterHardcoreOrEpicInformations;
         _typesTypes[3023] = EntityDispositionInformations;
         _typesTypes[6346] = IdentifiedEntityDispositionInformations;
         _typesTypes[8186] = FightEntityDispositionInformations;
         _typesTypes[6801] = AbstractSocialGroupInfos;
         _typesTypes[4801] = BasicGuildInformations;
         _typesTypes[5897] = GuildInformations;
         _typesTypes[9794] = GuildFactSheetInformations;
         _typesTypes[9940] = GuildInsiderFactSheetInformations;
         _typesTypes[274] = GuildInAllianceInformations;
         _typesTypes[8863] = AlliancedGuildFactSheetInformations;
         _typesTypes[1115] = BasicAllianceInformations;
         _typesTypes[4955] = BasicNamedAllianceInformations;
         _typesTypes[9961] = AllianceInformations;
         _typesTypes[1553] = AllianceFactSheetInformations;
         _typesTypes[1344] = GuildVersatileInformations;
         _typesTypes[8832] = GuildInAllianceVersatileInformations;
         _typesTypes[9794] = GuildFactSheetInformations;
         _typesTypes[9940] = GuildInsiderFactSheetInformations;
         _typesTypes[1553] = AllianceFactSheetInformations;
         _typesTypes[325] = PrismSubareaEmptyInfo;
         _typesTypes[946] = PrismGeolocalizedInformation;
         _typesTypes[1525] = PrismInformation;
         _typesTypes[1451] = AlliancePrismInformation;
         _typesTypes[3742] = AllianceInsiderPrismInformation;
         _typesTypes[4681] = FightTeamMemberInformations;
         _typesTypes[4605] = FightTeamMemberCharacterInformations;
         _typesTypes[9492] = FightTeamMemberWithAllianceCharacterInformations;
         _typesTypes[1174] = FightTeamMemberTaxCollectorInformations;
         _typesTypes[8154] = FightTeamMemberMonsterInformations;
         _typesTypes[4686] = FightTeamMemberEntityInformation;
         _typesTypes[6438] = FightTeamInformations;
         _typesTypes[2266] = FightAllianceTeamInformations;
         _typesTypes[7930] = GameFightMinimalStats;
         _typesTypes[4441] = GameFightMinimalStatsPreparation;
         _typesTypes[9494] = FightResultListEntry;
         _typesTypes[1126] = FightResultFighterListEntry;
         _typesTypes[2949] = FightResultTaxCollectorListEntry;
         _typesTypes[1038] = FightResultPlayerListEntry;
         _typesTypes[3438] = FightResultMutantListEntry;
         _typesTypes[1833] = FightResultAdditionalData;
         _typesTypes[9936] = FightResultPvpData;
         _typesTypes[5733] = FightResultExperienceData;
         _typesTypes[5728] = AbstractFightDispellableEffect;
         _typesTypes[2053] = FightTemporaryBoostEffect;
         _typesTypes[3882] = FightTemporaryBoostStateEffect;
         _typesTypes[846] = FightTemporarySpellBoostEffect;
         _typesTypes[6312] = FightTemporaryBoostWeaponDamagesEffect;
         _typesTypes[2653] = FightTemporarySpellImmunityEffect;
         _typesTypes[7490] = FightTriggeredEffect;
         _typesTypes[6605] = ObjectEffect;
         _typesTypes[5843] = ObjectEffectInteger;
         _typesTypes[7034] = ObjectEffectCreature;
         _typesTypes[1548] = ObjectEffectLadder;
         _typesTypes[5036] = ObjectEffectMinMax;
         _typesTypes[3785] = ObjectEffectDuration;
         _typesTypes[7628] = ObjectEffectString;
         _typesTypes[1846] = ObjectEffectDice;
         _typesTypes[5410] = ObjectEffectDate;
         _typesTypes[6975] = ObjectEffectMount;
         _typesTypes[8476] = UpdateMountCharacteristic;
         _typesTypes[3931] = UpdateMountBooleanCharacteristic;
         _typesTypes[8508] = UpdateMountIntegerCharacteristic;
         _typesTypes[1043] = Shortcut;
         _typesTypes[7541] = ShortcutObject;
         _typesTypes[2425] = ShortcutObjectPreset;
         _typesTypes[5835] = ShortcutObjectIdolsPreset;
         _typesTypes[4505] = ShortcutObjectItem;
         _typesTypes[571] = ShortcutSpell;
         _typesTypes[879] = ShortcutSmiley;
         _typesTypes[3412] = ShortcutEmote;
         _typesTypes[3594] = ShortcutEntitiesPreset;
         _typesTypes[2929] = Idol;
         _typesTypes[1051] = PartyIdol;
         _typesTypes[1051] = PartyIdol;
         _typesTypes[4690] = AchievementAchieved;
         _typesTypes[5008] = AchievementAchievedRewardable;
         _typesTypes[2408] = IgnoredInformations;
         _typesTypes[8804] = IgnoredOnlineInformations;
         _typesTypes[1820] = FriendInformations;
         _typesTypes[5289] = FriendOnlineInformations;
         _typesTypes[6697] = AcquaintanceInformation;
         _typesTypes[2613] = AcquaintanceOnlineInformation;
         _typesTypes[9044] = FriendSpouseInformations;
         _typesTypes[5625] = FriendSpouseOnlineInformations;
         _typesTypes[7363] = InteractiveElementSkill;
         _typesTypes[7588] = InteractiveElementNamedSkill;
         _typesTypes[4976] = InteractiveElement;
         _typesTypes[4190] = InteractiveElementWithAgeBonus;
         _typesTypes[213] = PartyMemberInformations;
         _typesTypes[6321] = PartyMemberArenaInformations;
         _typesTypes[7121] = PartyInvitationMemberInformations;
         _typesTypes[869] = PartyEntityBaseInformation;
         _typesTypes[6554] = PartyEntityMemberInformation;
         _typesTypes[3206] = SkillActionDescription;
         _typesTypes[7758] = SkillActionDescriptionTimed;
         _typesTypes[7961] = SkillActionDescriptionCollect;
         _typesTypes[8200] = SkillActionDescriptionCraft;
         _typesTypes[9215] = HouseInformations;
         _typesTypes[8630] = AccountHouseInformations;
         _typesTypes[6405] = HouseInformationsInside;
         _typesTypes[8727] = HouseInformationsForGuild;
         _typesTypes[4222] = HouseOnMapInformations;
         _typesTypes[1681] = HouseInstanceInformations;
         _typesTypes[3647] = HouseGuildedInformations;
         _typesTypes[3664] = PaddockBuyableInformations;
         _typesTypes[355] = PaddockGuildedInformations;
         _typesTypes[4155] = GameContextActorPositionInformations;
         _typesTypes[6228] = GameContextActorInformations;
         _typesTypes[6298] = GameFightFighterInformations;
         _typesTypes[2640] = GameFightAIInformations;
         _typesTypes[3277] = GameFightMonsterInformations;
         _typesTypes[4758] = GameFightMonsterWithAlignmentInformations;
         _typesTypes[8882] = GameFightTaxCollectorInformations;
         _typesTypes[5594] = GameFightFighterNamedInformations;
         _typesTypes[201] = GameFightCharacterInformations;
         _typesTypes[7640] = GameFightMutantInformations;
         _typesTypes[8660] = GameFightEntityInformation;
         _typesTypes[3191] = GameRolePlayActorInformations;
         _typesTypes[6486] = GameRolePlayNamedActorInformations;
         _typesTypes[1689] = GameRolePlayHumanoidInformations;
         _typesTypes[1099] = GameRolePlayMutantInformations;
         _typesTypes[3034] = GameRolePlayCharacterInformations;
         _typesTypes[6918] = GameRolePlayMountInformations;
         _typesTypes[9317] = GameRolePlayMerchantInformations;
         _typesTypes[863] = GameRolePlayNpcInformations;
         _typesTypes[3740] = GameRolePlayNpcWithQuestInformations;
         _typesTypes[9292] = GameRolePlayGroupMonsterInformations;
         _typesTypes[521] = GameRolePlayGroupMonsterWaveInformations;
         _typesTypes[8498] = GameRolePlayTreasureHintInformations;
         _typesTypes[487] = GameRolePlayTaxCollectorInformations;
         _typesTypes[4866] = GameRolePlayPrismInformations;
         _typesTypes[3053] = GameRolePlayPortalInformations;
         _typesTypes[6228] = GameContextActorInformations;
         _typesTypes[6298] = GameFightFighterInformations;
         _typesTypes[2640] = GameFightAIInformations;
         _typesTypes[3277] = GameFightMonsterInformations;
         _typesTypes[4758] = GameFightMonsterWithAlignmentInformations;
         _typesTypes[8882] = GameFightTaxCollectorInformations;
         _typesTypes[5594] = GameFightFighterNamedInformations;
         _typesTypes[201] = GameFightCharacterInformations;
         _typesTypes[7640] = GameFightMutantInformations;
         _typesTypes[8660] = GameFightEntityInformation;
         _typesTypes[3191] = GameRolePlayActorInformations;
         _typesTypes[6486] = GameRolePlayNamedActorInformations;
         _typesTypes[1689] = GameRolePlayHumanoidInformations;
         _typesTypes[1099] = GameRolePlayMutantInformations;
         _typesTypes[3034] = GameRolePlayCharacterInformations;
         _typesTypes[6918] = GameRolePlayMountInformations;
         _typesTypes[9317] = GameRolePlayMerchantInformations;
         _typesTypes[863] = GameRolePlayNpcInformations;
         _typesTypes[3740] = GameRolePlayNpcWithQuestInformations;
         _typesTypes[9292] = GameRolePlayGroupMonsterInformations;
         _typesTypes[521] = GameRolePlayGroupMonsterWaveInformations;
         _typesTypes[8498] = GameRolePlayTreasureHintInformations;
         _typesTypes[487] = GameRolePlayTaxCollectorInformations;
         _typesTypes[4866] = GameRolePlayPrismInformations;
         _typesTypes[3053] = GameRolePlayPortalInformations;
         _typesTypes[3191] = GameRolePlayActorInformations;
         _typesTypes[6486] = GameRolePlayNamedActorInformations;
         _typesTypes[1689] = GameRolePlayHumanoidInformations;
         _typesTypes[1099] = GameRolePlayMutantInformations;
         _typesTypes[3034] = GameRolePlayCharacterInformations;
         _typesTypes[6918] = GameRolePlayMountInformations;
         _typesTypes[9317] = GameRolePlayMerchantInformations;
         _typesTypes[863] = GameRolePlayNpcInformations;
         _typesTypes[3740] = GameRolePlayNpcWithQuestInformations;
         _typesTypes[9292] = GameRolePlayGroupMonsterInformations;
         _typesTypes[521] = GameRolePlayGroupMonsterWaveInformations;
         _typesTypes[8498] = GameRolePlayTreasureHintInformations;
         _typesTypes[487] = GameRolePlayTaxCollectorInformations;
         _typesTypes[4866] = GameRolePlayPrismInformations;
         _typesTypes[3053] = GameRolePlayPortalInformations;
         _typesTypes[6717] = HumanInformations;
         _typesTypes[4884] = HumanOption;
         _typesTypes[9970] = HumanOptionObjectUse;
         _typesTypes[4941] = HumanOptionAlliance;
         _typesTypes[5005] = HumanOptionGuild;
         _typesTypes[8260] = HumanOptionOrnament;
         _typesTypes[5243] = HumanOptionEmote;
         _typesTypes[7090] = HumanOptionTitle;
         _typesTypes[1429] = HumanOptionSkillUse;
         _typesTypes[7484] = HumanOptionFollowers;
         _typesTypes[3115] = TaxCollectorStaticInformations;
         _typesTypes[5888] = TaxCollectorStaticExtendedInformations;
         _typesTypes[5143] = TaxCollectorInformations;
         _typesTypes[9776] = TaxCollectorComplementaryInformations;
         _typesTypes[1607] = TaxCollectorGuildInformations;
         _typesTypes[2162] = TaxCollectorLootInformations;
         _typesTypes[7974] = TaxCollectorWaitingForHelpInformations;
         _typesTypes[5768] = GroupMonsterStaticInformations;
         _typesTypes[7681] = GroupMonsterStaticInformationsWithAlternatives;
         _typesTypes[2413] = QuestActiveInformations;
         _typesTypes[1795] = QuestActiveDetailedInformations;
         _typesTypes[2312] = QuestObjectiveInformations;
         _typesTypes[1770] = QuestObjectiveInformationsWithCompletion;
         _typesTypes[259] = SpawnInformation;
         _typesTypes[6339] = BaseSpawnMonsterInformation;
         _typesTypes[1659] = SpawnScaledMonsterInformation;
         _typesTypes[5401] = SpawnMonsterInformation;
         _typesTypes[5264] = SpawnCharacterInformation;
         _typesTypes[2859] = SpawnCompanionInformation;
         _typesTypes[2478] = GameContextBasicSpawnInformation;
         _typesTypes[3995] = GameContextSummonsInformation;
         _typesTypes[6298] = GameFightFighterInformations;
         _typesTypes[2640] = GameFightAIInformations;
         _typesTypes[3277] = GameFightMonsterInformations;
         _typesTypes[4758] = GameFightMonsterWithAlignmentInformations;
         _typesTypes[8882] = GameFightTaxCollectorInformations;
         _typesTypes[5594] = GameFightFighterNamedInformations;
         _typesTypes[201] = GameFightCharacterInformations;
         _typesTypes[7640] = GameFightMutantInformations;
         _typesTypes[8660] = GameFightEntityInformation;
         _typesTypes[4298] = GameFightFighterLightInformations;
         _typesTypes[873] = GameFightFighterMonsterLightInformations;
         _typesTypes[8213] = GameFightFighterNamedLightInformations;
         _typesTypes[5566] = GameFightFighterTaxCollectorLightInformations;
         _typesTypes[3866] = GameFightFighterEntityLightInformation;
         _typesTypes[5486] = MapCoordinates;
         _typesTypes[3427] = MapCoordinatesAndId;
         _typesTypes[8214] = MapCoordinatesExtended;
         _typesTypes[4804] = Preset;
         _typesTypes[9903] = PresetsContainerPreset;
         _typesTypes[7815] = IconNamedPreset;
         _typesTypes[2124] = SpellsPreset;
         _typesTypes[7595] = ForgettableSpellsPreset;
         _typesTypes[3738] = StatsPreset;
         _typesTypes[2799] = IdolsPreset;
         _typesTypes[527] = EntitiesPreset;
         _typesTypes[2296] = FullStatsPreset;
         _typesTypes[2193] = ItemsPreset;
         _typesTypes[2376] = TreasureHuntStep;
         _typesTypes[7529] = TreasureHuntStepFollowDirectionToPOI;
         _typesTypes[5817] = TreasureHuntStepDig;
         _typesTypes[7770] = TreasureHuntStepFight;
         _typesTypes[9917] = TreasureHuntStepFollowDirectionToHint;
         _typesTypes[3613] = TreasureHuntStepFollowDirection;
         _typesTypes[4544] = PortalInformation;
         _typesTypes[1023] = BreachBranch;
         _typesTypes[6573] = ExtendedBreachBranch;
         _typesTypes[1746] = ExtendedLockedBreachBranch;
         _typesTypes[6573] = ExtendedBreachBranch;
         _typesTypes[1746] = ExtendedLockedBreachBranch;
         _typesTypes[6393] = PlayerStatus;
         _typesTypes[865] = PlayerStatusExtended;
         _typesTypes[8194] = ServerSessionConstant;
         _typesTypes[6149] = ServerSessionConstantString;
         _typesTypes[8729] = ServerSessionConstantInteger;
         _typesTypes[9780] = ServerSessionConstantLong;
         _typesTypes[8706] = StatisticData;
         _typesTypes[8962] = StatisticDataInt;
         _typesTypes[9517] = StatisticDataBoolean;
         _typesTypes[760] = StatisticDataShort;
         _typesTypes[134] = StatisticDataString;
         _typesTypes[399] = StatisticDataByte;
         _typesTypes[7486] = DebtInformation;
         _typesTypes[6089] = KamaDebtInformation;
      }
      
      public function ProtocolTypeManager()
      {
         super();
      }
      
      public static function getInstance(base:Class, typeId:uint) : *
      {
         var objType:Class = _typesTypes[typeId];
         if(!objType)
         {
            throw new Error("Type with id " + typeId + " is unknown.");
         }
         var obj:* = new objType();
         if(!(obj is base))
         {
            throw new Error("Type " + typeId + " is not a " + base + ".");
         }
         return obj;
      }
      
      public static function register() : void
      {
         StoreDataManager.getInstance().registerClass(new CharacterMinimalPlusLookInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new CharacterBaseInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new PartyMemberInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new PartyMemberArenaInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new PartyInvitationMemberInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new CharacterHardcoreOrEpicInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new CharacterMinimalGuildInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new CharacterMinimalAllianceInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new CharacterMinimalPlusLookAndGradeInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new CharacterBaseInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new PartyMemberInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new PartyMemberArenaInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new PartyInvitationMemberInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new CharacterHardcoreOrEpicInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new EntityDispositionInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new IdentifiedEntityDispositionInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new FightEntityDispositionInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new AbstractSocialGroupInfos(),true,true);
         StoreDataManager.getInstance().registerClass(new BasicGuildInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GuildInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GuildFactSheetInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GuildInsiderFactSheetInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GuildInAllianceInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new AlliancedGuildFactSheetInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new BasicAllianceInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new BasicNamedAllianceInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new AllianceInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new AllianceFactSheetInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GuildVersatileInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GuildInAllianceVersatileInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GuildFactSheetInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GuildInsiderFactSheetInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new AllianceFactSheetInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new PrismSubareaEmptyInfo(),true,true);
         StoreDataManager.getInstance().registerClass(new PrismGeolocalizedInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new PrismInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new AlliancePrismInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new AllianceInsiderPrismInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new FightTeamMemberInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new FightTeamMemberCharacterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new FightTeamMemberWithAllianceCharacterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new FightTeamMemberTaxCollectorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new FightTeamMemberMonsterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new FightTeamMemberEntityInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new FightTeamInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new FightAllianceTeamInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightMinimalStats(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightMinimalStatsPreparation(),true,true);
         StoreDataManager.getInstance().registerClass(new FightResultListEntry(),true,true);
         StoreDataManager.getInstance().registerClass(new FightResultFighterListEntry(),true,true);
         StoreDataManager.getInstance().registerClass(new FightResultTaxCollectorListEntry(),true,true);
         StoreDataManager.getInstance().registerClass(new FightResultPlayerListEntry(),true,true);
         StoreDataManager.getInstance().registerClass(new FightResultMutantListEntry(),true,true);
         StoreDataManager.getInstance().registerClass(new FightResultAdditionalData(),true,true);
         StoreDataManager.getInstance().registerClass(new FightResultPvpData(),true,true);
         StoreDataManager.getInstance().registerClass(new FightResultExperienceData(),true,true);
         StoreDataManager.getInstance().registerClass(new AbstractFightDispellableEffect(),true,true);
         StoreDataManager.getInstance().registerClass(new FightTemporaryBoostEffect(),true,true);
         StoreDataManager.getInstance().registerClass(new FightTemporaryBoostStateEffect(),true,true);
         StoreDataManager.getInstance().registerClass(new FightTemporarySpellBoostEffect(),true,true);
         StoreDataManager.getInstance().registerClass(new FightTemporaryBoostWeaponDamagesEffect(),true,true);
         StoreDataManager.getInstance().registerClass(new FightTemporarySpellImmunityEffect(),true,true);
         StoreDataManager.getInstance().registerClass(new FightTriggeredEffect(),true,true);
         StoreDataManager.getInstance().registerClass(new ObjectEffect(),true,true);
         StoreDataManager.getInstance().registerClass(new ObjectEffectInteger(),true,true);
         StoreDataManager.getInstance().registerClass(new ObjectEffectCreature(),true,true);
         StoreDataManager.getInstance().registerClass(new ObjectEffectLadder(),true,true);
         StoreDataManager.getInstance().registerClass(new ObjectEffectMinMax(),true,true);
         StoreDataManager.getInstance().registerClass(new ObjectEffectDuration(),true,true);
         StoreDataManager.getInstance().registerClass(new ObjectEffectString(),true,true);
         StoreDataManager.getInstance().registerClass(new ObjectEffectDice(),true,true);
         StoreDataManager.getInstance().registerClass(new ObjectEffectDate(),true,true);
         StoreDataManager.getInstance().registerClass(new ObjectEffectMount(),true,true);
         StoreDataManager.getInstance().registerClass(new UpdateMountCharacteristic(),true,true);
         StoreDataManager.getInstance().registerClass(new UpdateMountBooleanCharacteristic(),true,true);
         StoreDataManager.getInstance().registerClass(new UpdateMountIntegerCharacteristic(),true,true);
         StoreDataManager.getInstance().registerClass(new Shortcut(),true,true);
         StoreDataManager.getInstance().registerClass(new ShortcutObject(),true,true);
         StoreDataManager.getInstance().registerClass(new ShortcutObjectPreset(),true,true);
         StoreDataManager.getInstance().registerClass(new ShortcutObjectIdolsPreset(),true,true);
         StoreDataManager.getInstance().registerClass(new ShortcutObjectItem(),true,true);
         StoreDataManager.getInstance().registerClass(new ShortcutSpell(),true,true);
         StoreDataManager.getInstance().registerClass(new ShortcutSmiley(),true,true);
         StoreDataManager.getInstance().registerClass(new ShortcutEmote(),true,true);
         StoreDataManager.getInstance().registerClass(new ShortcutEntitiesPreset(),true,true);
         StoreDataManager.getInstance().registerClass(new Idol(),true,true);
         StoreDataManager.getInstance().registerClass(new PartyIdol(),true,true);
         StoreDataManager.getInstance().registerClass(new PartyIdol(),true,true);
         StoreDataManager.getInstance().registerClass(new AchievementAchieved(),true,true);
         StoreDataManager.getInstance().registerClass(new AchievementAchievedRewardable(),true,true);
         StoreDataManager.getInstance().registerClass(new IgnoredInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new IgnoredOnlineInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new FriendInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new FriendOnlineInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new AcquaintanceInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new AcquaintanceOnlineInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new FriendSpouseInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new FriendSpouseOnlineInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new InteractiveElementSkill(),true,true);
         StoreDataManager.getInstance().registerClass(new InteractiveElementNamedSkill(),true,true);
         StoreDataManager.getInstance().registerClass(new InteractiveElement(),true,true);
         StoreDataManager.getInstance().registerClass(new InteractiveElementWithAgeBonus(),true,true);
         StoreDataManager.getInstance().registerClass(new PartyMemberInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new PartyMemberArenaInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new PartyInvitationMemberInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new PartyEntityBaseInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new PartyEntityMemberInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new SkillActionDescription(),true,true);
         StoreDataManager.getInstance().registerClass(new SkillActionDescriptionTimed(),true,true);
         StoreDataManager.getInstance().registerClass(new SkillActionDescriptionCollect(),true,true);
         StoreDataManager.getInstance().registerClass(new SkillActionDescriptionCraft(),true,true);
         StoreDataManager.getInstance().registerClass(new HouseInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new AccountHouseInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new HouseInformationsInside(),true,true);
         StoreDataManager.getInstance().registerClass(new HouseInformationsForGuild(),true,true);
         StoreDataManager.getInstance().registerClass(new HouseOnMapInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new HouseInstanceInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new HouseGuildedInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new PaddockBuyableInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new PaddockGuildedInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameContextActorPositionInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameContextActorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightFighterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightAIInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightMonsterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightMonsterWithAlignmentInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightTaxCollectorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightFighterNamedInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightCharacterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightMutantInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightEntityInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayActorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayNamedActorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayHumanoidInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayMutantInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayCharacterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayMountInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayMerchantInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayNpcInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayNpcWithQuestInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayGroupMonsterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayGroupMonsterWaveInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayTreasureHintInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayTaxCollectorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayPrismInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayPortalInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameContextActorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightFighterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightAIInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightMonsterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightMonsterWithAlignmentInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightTaxCollectorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightFighterNamedInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightCharacterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightMutantInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightEntityInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayActorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayNamedActorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayHumanoidInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayMutantInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayCharacterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayMountInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayMerchantInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayNpcInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayNpcWithQuestInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayGroupMonsterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayGroupMonsterWaveInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayTreasureHintInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayTaxCollectorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayPrismInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayPortalInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayActorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayNamedActorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayHumanoidInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayMutantInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayCharacterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayMountInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayMerchantInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayNpcInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayNpcWithQuestInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayGroupMonsterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayGroupMonsterWaveInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayTreasureHintInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayTaxCollectorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayPrismInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameRolePlayPortalInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new HumanInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new HumanOption(),true,true);
         StoreDataManager.getInstance().registerClass(new HumanOptionObjectUse(),true,true);
         StoreDataManager.getInstance().registerClass(new HumanOptionAlliance(),true,true);
         StoreDataManager.getInstance().registerClass(new HumanOptionGuild(),true,true);
         StoreDataManager.getInstance().registerClass(new HumanOptionOrnament(),true,true);
         StoreDataManager.getInstance().registerClass(new HumanOptionEmote(),true,true);
         StoreDataManager.getInstance().registerClass(new HumanOptionTitle(),true,true);
         StoreDataManager.getInstance().registerClass(new HumanOptionSkillUse(),true,true);
         StoreDataManager.getInstance().registerClass(new HumanOptionFollowers(),true,true);
         StoreDataManager.getInstance().registerClass(new TaxCollectorStaticInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new TaxCollectorStaticExtendedInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new TaxCollectorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new TaxCollectorComplementaryInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new TaxCollectorGuildInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new TaxCollectorLootInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new TaxCollectorWaitingForHelpInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GroupMonsterStaticInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GroupMonsterStaticInformationsWithAlternatives(),true,true);
         StoreDataManager.getInstance().registerClass(new QuestActiveInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new QuestActiveDetailedInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new QuestObjectiveInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new QuestObjectiveInformationsWithCompletion(),true,true);
         StoreDataManager.getInstance().registerClass(new SpawnInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new BaseSpawnMonsterInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new SpawnScaledMonsterInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new SpawnMonsterInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new SpawnCharacterInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new SpawnCompanionInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new GameContextBasicSpawnInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new GameContextSummonsInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightFighterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightAIInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightMonsterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightMonsterWithAlignmentInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightTaxCollectorInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightFighterNamedInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightCharacterInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightMutantInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightEntityInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightFighterLightInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightFighterMonsterLightInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightFighterNamedLightInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightFighterTaxCollectorLightInformations(),true,true);
         StoreDataManager.getInstance().registerClass(new GameFightFighterEntityLightInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new MapCoordinates(),true,true);
         StoreDataManager.getInstance().registerClass(new MapCoordinatesAndId(),true,true);
         StoreDataManager.getInstance().registerClass(new MapCoordinatesExtended(),true,true);
         StoreDataManager.getInstance().registerClass(new Preset(),true,true);
         StoreDataManager.getInstance().registerClass(new PresetsContainerPreset(),true,true);
         StoreDataManager.getInstance().registerClass(new IconNamedPreset(),true,true);
         StoreDataManager.getInstance().registerClass(new SpellsPreset(),true,true);
         StoreDataManager.getInstance().registerClass(new ForgettableSpellsPreset(),true,true);
         StoreDataManager.getInstance().registerClass(new StatsPreset(),true,true);
         StoreDataManager.getInstance().registerClass(new IdolsPreset(),true,true);
         StoreDataManager.getInstance().registerClass(new EntitiesPreset(),true,true);
         StoreDataManager.getInstance().registerClass(new FullStatsPreset(),true,true);
         StoreDataManager.getInstance().registerClass(new ItemsPreset(),true,true);
         StoreDataManager.getInstance().registerClass(new TreasureHuntStep(),true,true);
         StoreDataManager.getInstance().registerClass(new TreasureHuntStepFollowDirectionToPOI(),true,true);
         StoreDataManager.getInstance().registerClass(new TreasureHuntStepDig(),true,true);
         StoreDataManager.getInstance().registerClass(new TreasureHuntStepFight(),true,true);
         StoreDataManager.getInstance().registerClass(new TreasureHuntStepFollowDirectionToHint(),true,true);
         StoreDataManager.getInstance().registerClass(new TreasureHuntStepFollowDirection(),true,true);
         StoreDataManager.getInstance().registerClass(new PortalInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new BreachBranch(),true,true);
         StoreDataManager.getInstance().registerClass(new ExtendedBreachBranch(),true,true);
         StoreDataManager.getInstance().registerClass(new ExtendedLockedBreachBranch(),true,true);
         StoreDataManager.getInstance().registerClass(new ExtendedBreachBranch(),true,true);
         StoreDataManager.getInstance().registerClass(new ExtendedLockedBreachBranch(),true,true);
         StoreDataManager.getInstance().registerClass(new PlayerStatus(),true,true);
         StoreDataManager.getInstance().registerClass(new PlayerStatusExtended(),true,true);
         StoreDataManager.getInstance().registerClass(new ServerSessionConstant(),true,true);
         StoreDataManager.getInstance().registerClass(new ServerSessionConstantString(),true,true);
         StoreDataManager.getInstance().registerClass(new ServerSessionConstantInteger(),true,true);
         StoreDataManager.getInstance().registerClass(new ServerSessionConstantLong(),true,true);
         StoreDataManager.getInstance().registerClass(new StatisticData(),true,true);
         StoreDataManager.getInstance().registerClass(new StatisticDataInt(),true,true);
         StoreDataManager.getInstance().registerClass(new StatisticDataBoolean(),true,true);
         StoreDataManager.getInstance().registerClass(new StatisticDataShort(),true,true);
         StoreDataManager.getInstance().registerClass(new StatisticDataString(),true,true);
         StoreDataManager.getInstance().registerClass(new StatisticDataByte(),true,true);
         StoreDataManager.getInstance().registerClass(new DebtInformation(),true,true);
         StoreDataManager.getInstance().registerClass(new KamaDebtInformation(),true,true);
      }
   }
}
